mkdir: cannot create directory ‘/scratch/cwagen-gaussian’: File exists
cp: cannot create regular file ‘/scratch/cwagen-gaussian/run_gaussian.sh’: File exists
mkdir: cannot create directory ‘/scratch/cwagen-xtb’: File exists
cp: cannot create regular file ‘/scratch/cwagen-xtb/run_xtb.sh’: File exists
Loaded configuration data from /n/home03/cwagen/presto.config.
slurmstepd: error: *** JOB 6591371 ON holy7c08505 CANCELLED AT 2020-11-03T13:48:15 ***
