mkdir: cannot create directory ‘/scratch/cwagen-gaussian’: File exists
cp: cannot create regular file ‘/scratch/cwagen-gaussian/run_gaussian.sh’: File exists
mkdir: cannot create directory ‘/scratch/cwagen-xtb’: File exists
cp: cannot create regular file ‘/scratch/cwagen-xtb/run_xtb.sh’: File exists
slurmstepd: error: *** JOB 11896786 ON holy7c21310 CANCELLED AT 2021-01-04T09:12:50 DUE TO PREEMPTION ***
